modLoader="javafml" # Mandatory
loaderVersion="${loader_version_range}" # Mandatory
license="${mod_license}" # Mandatory
issueTrackerURL="https://github.com/SpokenWig620933/KubeJS_Keybinds/issues" # Optional

[[mods]] # Mandatory
modId="${mod_id}" # Mandatory
version="${mod_version}" # Mandatory
displayName="${mod_name}" # Mandatory
updateJSONURL="https://raw.githubusercontent.com/SpokenWig620933/KubeJS_Keybinds/master/update.json" # Optional - A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
displayURL="https://www.curseforge.com/minecraft/mc-mods/kubejs-keybinds" # Optional
logoFile= "kubejs_keybinds-logo.png" # Optional
credits="${mod_credits}" # Optional
authors="${mod_authors}" # Mandatory

# The description text for the mod (multi line!) (#mandatory)
description='''
KubeJS extension for KeyBinds
'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge" # Mandatory
    type="required" # Mandatory - The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
    # reason="..." # Optional - Field for describing why the dependency is required or why it is incompatible
    versionRange="[${neo_version},)" # Mandatory
    # An ordering relationship for the dependency.
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    side="CLIENT" # Mandatory - Side this dependency is applied on - BOTH, CLIENT, or SERVER

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="kubejs"
    type="required"
    versionRange="[${kubejs_version},)"
    ordering="NONE"
    side="CLIENT"