modLoader="javafml" # Mandatory
loaderVersion="[1,)" # Mandatory
license="${mod_license}" # Mandatory
issueTrackerURL="${mod_issues}" # Optional

[[mods]] # Mandatory
modId="${mod_id}" # Mandatory
version="${mod_version}" # Mandatory
displayName="${mod_name}" # Mandatory
updateJSONURL="${mod_update_neoforge}" # Optional - https://docs.neoforged.net/docs/misc/updatechecker/
displayURL="${mod_homepage}" # Optional
logoFile= "${mod_id}-logo.png" # Optional
credits="TheSavageWolf32 (Logo)" # Optional
authors="SpokenWig620933" # Mandatory

# The description text for the mod (multi line!) (#mandatory)
description='''
KubeJS extension for KeyBinds.
'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge" # Mandatory
    type="required" # Mandatory - ["required", "optional", "incompatible" or "discouraged"] (case insensitive).
    # reason="..." # Optional - Why is the dependency required or why it is incompatible.
    versionRange="[${neoforge_version},)" # Mandatory
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    side="CLIENT" # Mandatory - [BOTH, CLIENT, SERVER]

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="kubejs"
    type="required"
    versionRange="[${kubejs_version},)"
    ordering="NONE"
    side="CLIENT"